apiVersion: v2
name: codecourt
description: A Helm chart for CodeCourt - a coding judge system
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - codecourt
  - judge
  - coding
  - competition
maintainers:
  - name: CodeCourt Team
    email: team@codecourt.io

dependencies:
  - name: postgres-operator
    version: "1.10.1"
    repository: "https://opensource.zalando.com/postgres-operator/charts/postgres-operator"
    condition: postgres-operator.enabled
    alias: postgresql-operator
  - name: strimzi-kafka-operator
    version: "0.38.0"
    repository: "https://strimzi.io/charts/"
    condition: strimzi-kafka-operator.enabled
