apiVersion: v1
kind: Secret
metadata:
  name: {{ include "codecourt.fullname" . }}-api-gateway-secrets
  labels:
    {{- include "codecourt.labels" . | nindent 4 }}
    app.kubernetes.io/component: api-gateway
type: Opaque
data:
  {{- range $key, $value := .Values.apiGateway.env }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
