apiVersion: v1
kind: Service
metadata:
  name: {{ include "codecourt.fullname" . }}-jaeger
  labels:
    {{- include "codecourt.labels" . | nindent 4 }}
    app.kubernetes.io/component: jaeger
spec:
  type: {{ .Values.jaeger.service.type }}
  ports:
    - port: {{ .Values.jaeger.service.queryPort }}
      targetPort: query-http
      protocol: TCP
      name: query-http
    - port: {{ .Values.jaeger.service.collectorHttpPort }}
      targetPort: collector-http
      protocol: TCP
      name: collector-http
    - port: {{ .Values.jaeger.service.collectorGrpcPort }}
      targetPort: collector-grpc
      protocol: TCP
      name: collector-grpc
    - port: {{ .Values.jaeger.service.agentCompactPort }}
      targetPort: agent-compact
      protocol: UDP
      name: agent-compact
    - port: {{ .Values.jaeger.service.agentBinaryPort }}
      targetPort: agent-binary
      protocol: UDP
      name: agent-binary
    - port: {{ .Values.jaeger.service.agentConfigPort }}
      targetPort: agent-config
      protocol: TCP
      name: agent-config
    - port: {{ .Values.jaeger.service.zipkinPort }}
      targetPort: zipkin
      protocol: TCP
      name: zipkin
  selector:
    {{- include "codecourt.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: jaeger
