apiVersion: v1
kind: Secret
metadata:
  name: {{ include "codecourt.fullname" . }}-judging-service-secrets
  labels:
    {{- include "codecourt.labels" . | nindent 4 }}
    app.kubernetes.io/component: judging-service
type: Opaque
stringData:
  KAFKA_BROKERS: "codecourt-kafka-bootstrap:9092"
  KAFKA_GROUP_ID: "judging-service"
  KAFKA_TOPICS: "submission-events"
  MAX_EXECUTION_TIME: "10000"
  MAX_MEMORY_USAGE: "512M"
