{{- if .Values.kafka.enabled }}
{{- range .Values.kafka.topics }}
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: {{ .name }}
  namespace: {{ default $.Release.Namespace $.Values.kafka.namespace }}
  labels:
    {{- include "codecourt.labels" $ | nindent 4 }}
    app.kubernetes.io/component: messaging
    strimzi.io/cluster: {{ $.Values.kafka.name }}
spec:
  partitions: {{ .partitions }}
  replicas: {{ .replicas }}
  config:
    {{- range $key, $value := .config }}
    {{ $key }}: {{ $value }}
    {{- end }}
{{- end }}
{{- end }}
