{{- if .Values.kafka.enabled }}
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: {{ .Values.kafka.name }}
  namespace: {{ default .Release.Namespace .Values.kafka.namespace }}
  labels:
    {{- include "codecourt.labels" . | nindent 4 }}
    app.kubernetes.io/component: messaging
spec:
  kafka:
    version: 3.3.1
    replicas: {{ .Values.kafka.replicas }}
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
    config:
      {{- range $key, $value := .Values.kafka.config }}
      {{ $key }}: {{ $value }}
      {{- end }}
    storage:
      type: {{ .Values.kafka.storage.type }}
      size: {{ .Values.kafka.storage.size }}
      deleteClaim: {{ .Values.kafka.storage.deleteClaim }}
      {{- if .Values.kafka.storage.class }}
      class: {{ .Values.kafka.storage.class }}
      {{- end }}
    resources:
      requests:
        memory: {{ .Values.kafka.resources.requests.memory }}
        cpu: {{ .Values.kafka.resources.requests.cpu }}
      limits:
        memory: {{ .Values.kafka.resources.limits.memory }}
        cpu: {{ .Values.kafka.resources.limits.cpu }}
  zookeeper:
    replicas: {{ .Values.kafka.zookeeper.replicas }}
    storage:
      type: {{ .Values.kafka.zookeeper.storage.type }}
      size: {{ .Values.kafka.zookeeper.storage.size }}
      deleteClaim: {{ .Values.kafka.zookeeper.storage.deleteClaim }}
      {{- if .Values.kafka.zookeeper.storage.class }}
      class: {{ .Values.kafka.zookeeper.storage.class }}
      {{- end }}
    resources:
      requests:
        memory: {{ .Values.kafka.zookeeper.resources.requests.memory }}
        cpu: {{ .Values.kafka.zookeeper.resources.requests.cpu }}
      limits:
        memory: {{ .Values.kafka.zookeeper.resources.limits.memory }}
        cpu: {{ .Values.kafka.zookeeper.resources.limits.cpu }}
  entityOperator:
    topicOperator: {}
    userOperator: {}
{{- end }}
