apiVersion: v1
kind: Service
metadata:
  name: {{ include "codecourt.fullname" . }}-otel-collector
  labels:
    {{- include "codecourt.labels" . | nindent 4 }}
    app.kubernetes.io/component: otel-collector
spec:
  type: {{ .Values.otelCollector.service.type }}
  ports:
    - port: {{ .Values.otelCollector.service.otlpGrpcPort }}
      targetPort: otlp-grpc
      protocol: TCP
      name: otlp-grpc
    - port: {{ .Values.otelCollector.service.otlpHttpPort }}
      targetPort: otlp-http
      protocol: TCP
      name: otlp-http
    - port: {{ .Values.otelCollector.service.metricsPort }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "codecourt.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: otel-collector
