apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "codecourt.fullname" . }}-otel-collector-config
  labels:
    {{- include "codecourt.labels" . | nindent 4 }}
    app.kubernetes.io/component: otel-collector
data:
  otel-collector-config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
      
      # Enables metrics collection for Prometheus
      prometheus:
        config:
          scrape_configs:
            - job_name: 'otel-collector'
              scrape_interval: 10s
              static_configs:
                - targets: ['0.0.0.0:8888']
    
    processors:
      batch:
        timeout: 1s
        send_batch_size: 1024
      
      memory_limiter:
        check_interval: 1s
        limit_percentage: 75
        spike_limit_percentage: 15
      
      # Add resource attributes to all spans
      resource:
        attributes:
          - key: service.namespace
            value: codecourt
            action: upsert
    
    exporters:
      jaeger:
        endpoint: {{ include "codecourt.fullname" . }}-jaeger:14250
        tls:
          insecure: true
      
      prometheus:
        endpoint: 0.0.0.0:8889
      
      logging:
        loglevel: debug
    
    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [memory_limiter, batch, resource]
          exporters: [jaeger, logging]
        
        metrics:
          receivers: [otlp, prometheus]
          processors: [memory_limiter, batch, resource]
          exporters: [prometheus, logging]
