apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "codecourt.fullname" . }}-problem-service
  labels:
    {{- include "codecourt.labels" . | nindent 4 }}
    app.kubernetes.io/component: problem-service
spec:
  replicas: {{ .Values.problemService.replicaCount }}
  selector:
    matchLabels:
      {{- include "codecourt.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: problem-service
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "codecourt.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: problem-service
      annotations:
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        prometheus.io/scrape: "true"
        prometheus.io/port: "8888"
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "codecourt.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-problem-service
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.problemService.image.repository }}:{{ .Values.problemService.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env:
            - name: SERVER_PORT
              value: "{{ .Values.problemService.service.port }}"
            # OpenTelemetry configuration
            - name: OTEL_SERVICE_NAME
              value: "problem-service"
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: "service.namespace=codecourt,service.name=problem-service"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://{{ include "codecourt.fullname" . }}-otel-collector:4317"
            - name: OTEL_TRACES_SAMPLER
              value: "parentbased_traceidratio"
            - name: OTEL_TRACES_SAMPLER_ARG
              value: "1.0"
            - name: OTEL_PROPAGATORS
              value: "tracecontext,baggage,b3"
            {{- range $key, $value := .Values.problemService.env }}
            - name: {{ $key }}
              valueFrom:
                secretKeyRef:
                  name: {{ include "codecourt.fullname" $ }}-problem-service-secrets
                  key: {{ $key }}
            {{- end }}
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            {{- toYaml .Values.problemService.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
