apiVersion: v1
kind: Secret
metadata:
  name: {{ include "codecourt.fullname" . }}-problem-service-secrets
  labels:
    {{- include "codecourt.labels" . | nindent 4 }}
    app.kubernetes.io/component: problem-service
type: Opaque
data:
  {{- range $key, $value := .Values.problemService.env }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
