apiVersion: v1
kind: ServiceAccount
metadata:
  name: codecourt
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "codecourt.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
