apiVersion: v1
kind: Service
metadata:
  name: {{ include "codecourt.fullname" . }}-user-service
  labels:
    {{- include "codecourt.labels" . | nindent 4 }}
    app.kubernetes.io/component: user-service
spec:
  type: {{ .Values.userService.service.type }}
  ports:
    - port: {{ .Values.userService.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "codecourt.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: user-service
